-- SQLite
CREATE TABLE account(
  ID INTEGER PRIMARY KEY,
  OPENID TEXT UNIQUE,
  SUPERUSER BOOL DEFAULT FALSE,
  NICKNAME TEXT DEFAULT ''
);

CREATE TABLE account_likes(
    UID INTEGER NOT NULL,
    PID INTEGER NOT NULL,
    ADD_DATE INTEGER DEFAULT now,
    PRIMARY KEY (UID, PID)
);
CREATE TABLE account_favors(
    UID INTEGER NOT NULL,
    PID INTEGER NOT NULL,
    ADD_DATE INTEGER DEFAULT now,
    PRIMARY KEY (UID, PID)
);